version: "3.8"

services:
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/crud_demo

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/crud_demo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: composer install --ignore-platform-reqs
    depends_on:
      - php
